"""Create cms_submissions table

Revision ID: 001_cms_submissions
Revises: 
Create Date: 2026-05-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '001_cms_submissions'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cms_submissions',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('facility_id', sa.String(36), nullable=False),
        sa.Column('facility_name', sa.String(255), nullable=False),
        sa.Column('cms_provider_id', sa.String(10), nullable=False),
        sa.Column('submission_type', sa.String(50), nullable=False),
        sa.Column('status', sa.String(50), nullable=False, server_default='PENDING'),
        sa.Column('data_format', sa.String(20), nullable=True),
        sa.Column('data_version', sa.String(20), nullable=True),
        sa.Column('submission_data', sa.Text(), nullable=True),
        sa.Column('validation_passed', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('validation_errors', sa.JSON(), nullable=True),
        sa.Column('cms_response', sa.JSON(), nullable=True),
        sa.Column('cms_confirmation_id', sa.String(100), nullable=True),
        sa.Column('submission_date', sa.DateTime(), nullable=False),
        sa.Column('cms_response_date', sa.DateTime(), nullable=True),
        sa.Column('last_retry_date', sa.DateTime(), nullable=True),
        sa.Column('submitted_by', sa.String(255), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('submission_batch_id', sa.String(36), nullable=True),
        sa.Column('record_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
        sa.Index('idx_cms_submission_facility', 'facility_id'),
        sa.Index('idx_cms_submission_status', 'status'),
        sa.Index('idx_cms_submission_date', 'submission_date'),
        sa.Index('idx_cms_submission_batch', 'submission_batch_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_submissions')
    # ### end Alembic commands ###
